# .scrutinizer.yml - see https://scrutinizer-ci.com/docs/guides/php/continuous-integration-deployment for doc
build:
    environment:
        php:
            version: 5.6.0
            ini:
                'date.timezone': 'US/Pacific'
                'phar.readonly': false
        hosts:
            my.chamilodev.net: '127.0.0.1'
    dependencies:
        before:
            - composer -v update
filter:
    excluded_paths:
        - tests/*
        - main/img/*
        - main/lang/*
        - app/cache/*
        - app/logs/*
        - web/*
        - vendor/*
        - main/admin/db.php
        - app/Migrations/*
checks:
    php:
        code_rating: true
        duplication: true
